// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaelishpkdvqhtphmznl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZWxpc2hwa2R2cWh0cGhtem5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDUwNzgsImV4cCI6MjA2OTEyMTA3OH0.ii0Gmta-cZgWIHLHgOR-F3s_6ow4U-fsNgnjpFRvfzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});